M48
; DRILL file {KiCad 9.0.4} date 2025-10-04T22:47:16-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-04T22:47:16-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X113.0Y-60.0
X113.0Y-142.0
X239.5Y-60.0
X239.5Y-142.0
M30
